// <auto-generated />
using System;
using AtividadeMVC_.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AtividadeMVC_.Migrations
{
    [DbContext(typeof(AtividadeMVC_Context))]
    [Migration("20240430115929_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AtividadeMVC_.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Escola");

                    b.Property<string>("IdRM");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("AtividadeMVC_.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlunoId");

                    b.Property<string>("Escola");

                    b.Property<string>("IdRM");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Professor");
                });

            modelBuilder.Entity("AtividadeMVC_.Models.Professor", b =>
                {
                    b.HasOne("AtividadeMVC_.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId");
                });
#pragma warning restore 612, 618
        }
    }
}
