
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 23180
 */
public class FormVotacao extends javax.swing.JFrame {
    Votacao vot = new Votacao();
    /**
     * Creates new form FormVotacao
     */
    public FormVotacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonCand1 = new javax.swing.JButton();
        buttonCand2 = new javax.swing.JButton();
        buttonCand3 = new javax.swing.JButton();
        buttonCand4 = new javax.swing.JButton();
        buttonCand5 = new javax.swing.JButton();
        buttonApurar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCandvenc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCand1 = new javax.swing.JTextField();
        txtCand2 = new javax.swing.JTextField();
        txtCand3 = new javax.swing.JTextField();
        txtCand4 = new javax.swing.JTextField();
        txtCand5 = new javax.swing.JTextField();
        txtNvotoscand1 = new javax.swing.JTextField();
        txtNvotoscand2 = new javax.swing.JTextField();
        txtNvotoscand3 = new javax.swing.JTextField();
        txtNvotoscand4 = new javax.swing.JTextField();
        txtNvotoscand5 = new javax.swing.JTextField();
        txtPorcand1 = new javax.swing.JTextField();
        txtPorcand2 = new javax.swing.JTextField();
        txtPorcand3 = new javax.swing.JTextField();
        txtPorcand4 = new javax.swing.JTextField();
        txtPorcand5 = new javax.swing.JTextField();
        buttonSair = new javax.swing.JButton();
        buttonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 255));
        jLabel1.setText("ESCOLHA O CANDIDATO");

        buttonCand1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jonathan Menezes\\OneDrive\\Documentos\\NetBeans Projects\\ProjVotacaoOO\\img\\isaqueduro.png")); // NOI18N
        buttonCand1.setMaximumSize(new java.awt.Dimension(479, 407));
        buttonCand1.setMinimumSize(new java.awt.Dimension(479, 407));
        buttonCand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCand1ActionPerformed(evt);
            }
        });

        buttonCand2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jonathan Menezes\\OneDrive\\Documentos\\NetBeans Projects\\ProjVotacaoOO\\img\\tiririca.png")); // NOI18N
        buttonCand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCand2ActionPerformed(evt);
            }
        });

        buttonCand3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jonathan Menezes\\OneDrive\\Documentos\\NetBeans Projects\\ProjVotacaoOO\\img\\marco.png")); // NOI18N
        buttonCand3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCand3ActionPerformed(evt);
            }
        });

        buttonCand4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jonathan Menezes\\OneDrive\\Documentos\\NetBeans Projects\\ProjVotacaoOO\\img\\bolsonabo.png")); // NOI18N
        buttonCand4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCand4ActionPerformed(evt);
            }
        });

        buttonCand5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jonathan Menezes\\OneDrive\\Documentos\\NetBeans Projects\\ProjVotacaoOO\\img\\chaves.png")); // NOI18N
        buttonCand5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCand5ActionPerformed(evt);
            }
        });

        buttonApurar.setText("Apurar");
        buttonApurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonApurarActionPerformed(evt);
            }
        });

        jLabel2.setText("Candidato Vencedor:");

        txtCandvenc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCandvencActionPerformed(evt);
            }
        });

        jLabel3.setText("Percentuais");

        jLabel4.setText("Candidato");

        jLabel5.setText("N* Votos");

        jLabel6.setText("Porcentagem");

        txtCand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCand1ActionPerformed(evt);
            }
        });

        txtNvotoscand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNvotoscand1ActionPerformed(evt);
            }
        });

        txtNvotoscand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNvotoscand2ActionPerformed(evt);
            }
        });

        txtNvotoscand3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNvotoscand3ActionPerformed(evt);
            }
        });

        txtNvotoscand4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNvotoscand4ActionPerformed(evt);
            }
        });

        txtNvotoscand5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNvotoscand5ActionPerformed(evt);
            }
        });

        buttonSair.setBackground(new java.awt.Color(255, 51, 51));
        buttonSair.setForeground(new java.awt.Color(255, 255, 255));
        buttonSair.setText("Sair");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel4))
                                    .addComponent(txtCand3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCand1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCand2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCand5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCand4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNvotoscand1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNvotoscand5)
                                        .addComponent(txtNvotoscand3)
                                        .addComponent(txtNvotoscand2)
                                        .addComponent(txtNvotoscand4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtPorcand2)
                                                .addComponent(txtPorcand5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtPorcand1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtPorcand4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtPorcand3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonApurar)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(txtCandvenc, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(buttonLimpar))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(buttonCand1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCand2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(buttonCand3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCand4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSair)
                            .addComponent(buttonCand5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonCand5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCand4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCand2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCand1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCand3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonApurar)
                    .addComponent(buttonLimpar))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCandvenc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNvotoscand5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCand1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNvotoscand1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCand3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNvotoscand4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCand2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNvotoscand2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCand5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNvotoscand3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addComponent(txtCand4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPorcand2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPorcand1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPorcand4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPorcand5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPorcand3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(buttonSair)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCand2ActionPerformed
        vot.voto2();
        JOptionPane.showMessageDialog(null,"VOTO CADASTRADO!");
    }//GEN-LAST:event_buttonCand2ActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonApurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonApurarActionPerformed
        this.txtCand1.setText(""+vot.getCand1());
        this.txtCand3.setText(""+vot.getCand2());
        this.txtCand2.setText(""+vot.getCand3());
        this.txtCand5.setText(""+vot.getCand4());
        this.txtCand4.setText(""+vot.getCand5());
        this.txtNvotoscand1.setText(""+vot.getNv1());
        this.txtNvotoscand4.setText(""+vot.getNv2());
        this.txtNvotoscand2.setText(""+vot.getNv3());
        this.txtNvotoscand3.setText(""+vot.getNv4());
        this.txtNvotoscand5.setText(""+vot.getNv5());
        this.txtPorcand2.setText(vot.getPerc1()+"%");
        this.txtPorcand1.setText(vot.getPerc2()+"%");
        this.txtPorcand4.setText(vot.getPerc3()+"%");
        this.txtPorcand3.setText(vot.getPerc4()+"%");
        this.txtPorcand5.setText(vot.getPerc5()+"%");
        
        int i;
        int maximo = 0;
        int[]votos={vot.getNv1(),vot.getNv2(),vot.getNv3(),vot.getNv4(),vot.getNv5()};
        String[]candidatos={vot.getCand1(),vot.getCand2(),vot.getCand3(),vot.getCand4(),vot.getCand5()};
        for (i=1; i < votos.length; i++) {
            if (votos[i] > votos[maximo]) {
                maximo = i;
            }
        }
        this.txtCandvenc.setText(""+candidatos[maximo]);
    }//GEN-LAST:event_buttonApurarActionPerformed

    private void buttonCand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCand1ActionPerformed
        vot.voto1();
        JOptionPane.showMessageDialog(null,"VOTO CADASTRADO!");
    }//GEN-LAST:event_buttonCand1ActionPerformed

    private void txtNvotoscand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNvotoscand1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNvotoscand1ActionPerformed

    private void buttonCand3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCand3ActionPerformed
        vot.voto3();
        JOptionPane.showMessageDialog(null,"VOTO CADASTRADO!");
    }//GEN-LAST:event_buttonCand3ActionPerformed

    private void buttonCand4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCand4ActionPerformed
        vot.voto4();
        JOptionPane.showMessageDialog(null,"VOTO CADASTRADO!");
    }//GEN-LAST:event_buttonCand4ActionPerformed

    private void buttonCand5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCand5ActionPerformed
        vot.voto5();
        JOptionPane.showMessageDialog(null,"VOTO CADASTRADO!");
    }//GEN-LAST:event_buttonCand5ActionPerformed

    private void txtNvotoscand4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNvotoscand4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNvotoscand4ActionPerformed

    private void txtNvotoscand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNvotoscand2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNvotoscand2ActionPerformed

    private void txtNvotoscand3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNvotoscand3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNvotoscand3ActionPerformed

    private void txtNvotoscand5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNvotoscand5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNvotoscand5ActionPerformed

    private void txtCand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCand1ActionPerformed
    
    }//GEN-LAST:event_txtCand1ActionPerformed

    private void txtCandvencActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCandvencActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCandvencActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        this.txtCand1.setText("");
        this.txtCand3.setText("");
        this.txtCand2.setText("");
        this.txtCand5.setText("");
        this.txtCand4.setText("");
        this.txtNvotoscand1.setText("");
        this.txtNvotoscand4.setText("");
        this.txtNvotoscand2.setText("");
        this.txtNvotoscand3.setText("");
        this.txtNvotoscand5.setText("");
        this.txtPorcand2.setText("");
        this.txtPorcand1.setText("");
        this.txtPorcand4.setText("");
        this.txtPorcand3.setText("");
        this.txtPorcand5.setText("");
        this.txtCandvenc.setText("");
        vot.setNv1(0);
        vot.setNv2(0);
        vot.setNv3(0);
        vot.setNv4(0);
        vot.setNv5(0);
        vot.setTtlvotos(0);
        vot.setPerc1(0);
        vot.setPerc2(0);
        vot.setPerc3(0);
        vot.setPerc4(0);
        vot.setPerc5(0);
    }//GEN-LAST:event_buttonLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVotacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonApurar;
    private javax.swing.JButton buttonCand1;
    private javax.swing.JButton buttonCand2;
    private javax.swing.JButton buttonCand3;
    private javax.swing.JButton buttonCand4;
    private javax.swing.JButton buttonCand5;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCand1;
    private javax.swing.JTextField txtCand2;
    private javax.swing.JTextField txtCand3;
    private javax.swing.JTextField txtCand4;
    private javax.swing.JTextField txtCand5;
    private javax.swing.JTextField txtCandvenc;
    private javax.swing.JTextField txtNvotoscand1;
    private javax.swing.JTextField txtNvotoscand2;
    private javax.swing.JTextField txtNvotoscand3;
    private javax.swing.JTextField txtNvotoscand4;
    private javax.swing.JTextField txtNvotoscand5;
    private javax.swing.JTextField txtPorcand1;
    private javax.swing.JTextField txtPorcand2;
    private javax.swing.JTextField txtPorcand3;
    private javax.swing.JTextField txtPorcand4;
    private javax.swing.JTextField txtPorcand5;
    // End of variables declaration//GEN-END:variables
}
